export const themes = {
  light: {
    backgroundColor: "#ffffff",
    textColor: "#111111",
    textSecondary: "#666666",
    primaryColor: "#2563eb",
    axisColor: "#cccccc",
    fontFamily: "Arial, sans-serif",
  },
  dark: {
    backgroundColor: "#0f172a",
    textColor: "#f8fafc",
    textSecondary: "#94a3b8",
    primaryColor: "#3b82f6",
    axisColor: "#334155",
    fontFamily: "Arial, sans-serif",
  },
  finance: {
    backgroundColor: "#0B1220",
    textColor: "#E5E7EB",
    textSecondary: "#9CA3AF",
    primaryColor: "#00E676",
    axisColor: "#2A3441",
    gridColor: "#1F2937",
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
  },
  netflix: {
    backgroundColor: "#000000",
    textColor: "#FFFFFF",
    textSecondary: "#B3B3B3",
    primaryColor: "#E50914",
    axisColor: "#2A2A2A",
    gridColor: "#1A1A1A",
    fontFamily: "Helvetica Neue, Arial, sans-serif",
  },
  dw: {
    backgroundColor: "#F5F7FA",
    textColor: "#111827",
    textSecondary: "#6B7280",
    primaryColor: "#0055A4",
    axisColor: "#D1D5DB",
    gridColor: "#E5E7EB",
    fontFamily: "Inter, Arial, sans-serif",
  },
  bloomberg: {
    backgroundColor: "#0A0F1C",
    textColor: "#E6E8EB",
    textSecondary: "#9AA4AF",
    primaryColor: "#00FFB3",
    axisColor: "#1F2937",
    gridColor: "#111827",
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
  }
}